//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySys.Globalization.Fa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldicContractMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldicContractMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaySys.Globalization.Fa.FieldicContractMaster", typeof(FieldicContractMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب پرسنل.
        /// </summary>
        public static string AccountNoEmp {
            get {
                return ResourceManager.GetString("AccountNoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب دولت.
        /// </summary>
        public static string AccountNoGov {
            get {
                return ResourceManager.GetString("AccountNoGov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات حکم.
        /// </summary>
        public static string ContractDetails {
            get {
                return ResourceManager.GetString("ContractDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید اصلی.
        /// </summary>
        public static string ContractMasterId {
            get {
                return ResourceManager.GetString("ContractMasterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حکم.
        /// </summary>
        public static string ContractNo {
            get {
                return ResourceManager.GetString("ContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ استخدام.
        /// </summary>
        public static string DateEmployment {
            get {
                return ResourceManager.GetString("DateEmployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اجرا.
        /// </summary>
        public static string DateExecution {
            get {
                return ResourceManager.GetString("DateExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ صدور.
        /// </summary>
        public static string DateExport {
            get {
                return ResourceManager.GetString("DateExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرک تحصیلی.
        /// </summary>
        public static string EducationStand {
            get {
                return ResourceManager.GetString("EducationStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع استخدام.
        /// </summary>
        public static string EmploymentType {
            get {
                return ResourceManager.GetString("EmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضریب کار سخت.
        /// </summary>
        public static string HardshipFactor {
            get {
                return ResourceManager.GetString("HardshipFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره بیمه.
        /// </summary>
        public static string InsuranceNo {
            get {
                return ResourceManager.GetString("InsuranceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حکم جاری است.
        /// </summary>
        public static string IsCurrentContract {
            get {
                return ResourceManager.GetString("IsCurrentContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شغل.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تأهل.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت ایثارگری.
        /// </summary>
        public static string SacrificeStand {
            get {
                return ResourceManager.GetString("SacrificeStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر گروه.
        /// </summary>
        public static string SubGroup {
            get {
                return ResourceManager.GetString("SubGroup", resourceCulture);
            }
        }
    }
}
