//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySys.Globalization.Fa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldicMissionFormula {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldicMissionFormula() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaySys.Globalization.Fa.FieldicMissionFormula", typeof(FieldicMissionFormula).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعلاوه.
        /// </summary>
        public static string AddFactor {
            get {
                return ResourceManager.GetString("AddFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقسیم بر.
        /// </summary>
        public static string DivideFactor {
            get {
                return ResourceManager.GetString("DivideFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا سقف.
        /// </summary>
        public static string MaxFactor {
            get {
                return ResourceManager.GetString("MaxFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید فرمول مأموریت.
        /// </summary>
        public static string MissionFormulaId {
            get {
                return ResourceManager.GetString("MissionFormulaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلدهای احکام دخیل در فرمول مأموریت.
        /// </summary>
        public static string MissionFormulaInvolvedContractFields {
            get {
                return ResourceManager.GetString("MissionFormulaInvolvedContractFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرگروه.
        /// </summary>
        public static string SubGroup {
            get {
                return ResourceManager.GetString("SubGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع فیلدهای منتخب منهای.
        /// </summary>
        public static string SubtractFactor {
            get {
                return ResourceManager.GetString("SubtractFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
