//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySys.Globalization.Fa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldicMission {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldicMission() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaySys.Globalization.Fa.FieldicMission", typeof(FieldicMission).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت بدون بیتوته.
        /// </summary>
        public static string AmountNonResident {
            get {
                return ResourceManager.GetString("AmountNonResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت با بیتوته.
        /// </summary>
        public static string AmountResident {
            get {
                return ResourceManager.GetString("AmountResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل مأموریت.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایه حکم.
        /// </summary>
        public static string ContractMaster {
            get {
                return ResourceManager.GetString("ContractMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ مراجعت.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ عزیمت.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حکم مأموریت.
        /// </summary>
        public static string MissionContractNo {
            get {
                return ResourceManager.GetString("MissionContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید حکم مأموریت.
        /// </summary>
        public static string MissionId {
            get {
                return ResourceManager.GetString("MissionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان مراجعت.
        /// </summary>
        public static string TimeEnd {
            get {
                return ResourceManager.GetString("TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان عزیمت.
        /// </summary>
        public static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان مأموریت.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه سفر.
        /// </summary>
        public static string TravelExpense {
            get {
                return ResourceManager.GetString("TravelExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسیله نقلیه.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
    }
}
