//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySys.Globalization.Fa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaySys.Globalization.Fa.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فیلد حکم.
        /// </summary>
        public static string AddContractField {
            get {
                return ResourceManager.GetString("AddContractField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید (ورود جزئیات).
        /// </summary>
        public static string AddDetails {
            get {
                return ResourceManager.GetString("AddDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه اصلی جدید.
        /// </summary>
        public static string AddMainGroup {
            get {
                return ResourceManager.GetString("AddMainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید (ورود اطلاعات پایه).
        /// </summary>
        public static string AddMaster {
            get {
                return ResourceManager.GetString("AddMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن فیلد حکم دخیل در محاسبه مؤلفه.
        /// </summary>
        public static string AddParameterInvolvedContractField {
            get {
                return ResourceManager.GetString("AddParameterInvolvedContractField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن پرداخت متفرقه دخیل در محاسبه مؤلفه.
        /// </summary>
        public static string AddParameterInvolvedMiscPayment {
            get {
                return ResourceManager.GetString("AddParameterInvolvedMiscPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر گروه جدید.
        /// </summary>
        public static string AddSubGroup {
            get {
                return ResourceManager.GetString("AddSubGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حرکت خودکار به رکورد بعدی.
        /// </summary>
        public static string AutoMoveNext {
            get {
                return ResourceManager.GetString("AutoMoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر ماده هزینه.
        /// </summary>
        public static string ChangeExpenseArticle {
            get {
                return ResourceManager.GetString("ChangeExpenseArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرها.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شهر.
        /// </summary>
        public static string CityInfo {
            get {
                return ResourceManager.GetString("CityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حکم.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات حکم.
        /// </summary>
        public static string ContractDetails {
            get {
                return ResourceManager.GetString("ContractDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلدهای احکام.
        /// </summary>
        public static string ContractFields {
            get {
                return ResourceManager.GetString("ContractFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناوین فیلدهای احکام.
        /// </summary>
        public static string ContractFieldTitles {
            get {
                return ResourceManager.GetString("ContractFieldTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایه حکم.
        /// </summary>
        public static string ContractMaster {
            get {
                return ResourceManager.GetString("ContractMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فیلد حکم.
        /// </summary>
        public static string DeleteContractField {
            get {
                return ResourceManager.GetString("DeleteContractField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فیلد حکم دخیل در محاسبه مؤلفه.
        /// </summary>
        public static string DeleteParameterInvolvedContractField {
            get {
                return ResourceManager.GetString("DeleteParameterInvolvedContractField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف پرداخت متفرقه دخیل در محاسبه مؤلفه.
        /// </summary>
        public static string DeleteParameterInvolvedMiscPayment {
            get {
                return ResourceManager.GetString("DeleteParameterInvolvedMiscPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش نرخ.
        /// </summary>
        public static string EditRate {
            get {
                return ResourceManager.GetString("EditRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش عنوان.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مقدار.
        /// </summary>
        public static string EditValue {
            get {
                return ResourceManager.GetString("EditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمندان.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماده هزینه.
        /// </summary>
        public static string ExpenseArticle {
            get {
                return ResourceManager.GetString("ExpenseArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ماده هزینه.
        /// </summary>
        public static string ExpenseArticleInfo {
            get {
                return ResourceManager.GetString("ExpenseArticleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد هزینه.
        /// </summary>
        public static string ExpenseArticles {
            get {
                return ResourceManager.GetString("ExpenseArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرخ.
        /// </summary>
        public static string Factor {
            get {
                return ResourceManager.GetString("Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالت جاری فرم.
        /// </summary>
        public static string FormCurrentState {
            get {
                return ResourceManager.GetString("FormCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به تفکیک اشخاص.
        /// </summary>
        public static string GroupByEmployees {
            get {
                return ResourceManager.GetString("GroupByEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به تفکیک عناوین بدهی.
        /// </summary>
        public static string GroupByMiscTitle {
            get {
                return ResourceManager.GetString("GroupByMiscTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به تفکیک عناوین (کسور).
        /// </summary>
        public static string GroupByMiscTitleDebt {
            get {
                return ResourceManager.GetString("GroupByMiscTitleDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به تفکیک عناوین (پرداخت ها).
        /// </summary>
        public static string GroupByMiscTitlePayment {
            get {
                return ResourceManager.GetString("GroupByMiscTitlePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به تفکیک عناوین.
        /// </summary>
        public static string GroupByTitles {
            get {
                return ResourceManager.GetString("GroupByTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به تفکیک عناوین (متغیرها).
        /// </summary>
        public static string GroupByVariableTitle {
            get {
                return ResourceManager.GetString("GroupByVariableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمول عیدی.
        /// </summary>
        public static string HandselFormula {
            get {
                return ResourceManager.GetString("HandselFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (حکم جاری).
        /// </summary>
        public static string IsCurrentContractForCombobox {
            get {
                return ResourceManager.GetString("IsCurrentContractForCombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخیل در محاسبات.
        /// </summary>
        public static string IsInvolved {
            get {
                return ResourceManager.GetString("IsInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شغل ها.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه اصلی.
        /// </summary>
        public static string MainGroup {
            get {
                return ResourceManager.GetString("MainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم های مربوط به گروه اصلی.
        /// </summary>
        public static string MainGroupItems {
            get {
                return ResourceManager.GetString("MainGroupItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست گروه های اصلی.
        /// </summary>
        public static string MainGroupsList {
            get {
                return ResourceManager.GetString("MainGroupsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسور متفرقه.
        /// </summary>
        public static string MiscDebts {
            get {
                return ResourceManager.GetString("MiscDebts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدهیها و پرداختهای متفرقه.
        /// </summary>
        public static string MiscMng {
            get {
                return ResourceManager.GetString("MiscMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت های متفرقه.
        /// </summary>
        public static string MiscPayments {
            get {
                return ResourceManager.GetString("MiscPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناوین پرداخت ها و کسور متفرقه.
        /// </summary>
        public static string MiscTitles {
            get {
                return ResourceManager.GetString("MiscTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مأموریت.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات حکم مأموریت.
        /// </summary>
        public static string MissionDetail {
            get {
                return ResourceManager.GetString("MissionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمول مأموریت.
        /// </summary>
        public static string MissionFormula {
            get {
                return ResourceManager.GetString("MissionFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلدهای احکام دخیل در محاسبه مأموریت.
        /// </summary>
        public static string MissionFormulaInvolvedContractFields {
            get {
                return ResourceManager.GetString("MissionFormulaInvolvedContractFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احکام مأموریت.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متغیرهای ماهانه.
        /// </summary>
        public static string MonthlyVariables {
            get {
                return ResourceManager.GetString("MonthlyVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کارها.
        /// </summary>
        public static string OverTimes {
            get {
                return ResourceManager.GetString("OverTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلدهای احکام دخیل در محاسبه.
        /// </summary>
        public static string ParameterInvolvedContractFields {
            get {
                return ResourceManager.GetString("ParameterInvolvedContractFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداختهای متفرقه دخیل در محاسبه.
        /// </summary>
        public static string ParameterInvolvedMiscPayments {
            get {
                return ResourceManager.GetString("ParameterInvolvedMiscPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤلفه های محاسباتی.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان مؤلفه محاسباتی.
        /// </summary>
        public static string ParameterTitle {
            get {
                return ResourceManager.GetString("ParameterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار پارامتر.
        /// </summary>
        public static string ParameterValue {
            get {
                return ResourceManager.GetString("ParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات فردی.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مربوطه.
        /// </summary>
        public static string RelatedInfo {
            get {
                return ResourceManager.GetString("RelatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره و ورود جزئیات.
        /// </summary>
        public static string SaveContractMasterAndContinueToContractDetails {
            get {
                return ResourceManager.GetString("SaveContractMasterAndContinueToContractDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string SignOfDivide {
            get {
                return ResourceManager.GetString("SignOfDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string SignOfMinus {
            get {
                return ResourceManager.GetString("SignOfMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string SignOfMultiply {
            get {
                return ResourceManager.GetString("SignOfMultiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string SignOfPlus {
            get {
                return ResourceManager.GetString("SignOfPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر گروه.
        /// </summary>
        public static string SubGroup {
            get {
                return ResourceManager.GetString("SubGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم های مربوط به زیرگروه.
        /// </summary>
        public static string SubGroupItems {
            get {
                return ResourceManager.GetString("SubGroupItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست زیر گروه ها.
        /// </summary>
        public static string SubGroupsList {
            get {
                return ResourceManager.GetString("SubGroupsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ».
        /// </summary>
        public static string SurrounderOfFieldNameEnd {
            get {
                return ResourceManager.GetString("SurrounderOfFieldNameEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «.
        /// </summary>
        public static string SurrounderOfFieldNameStart {
            get {
                return ResourceManager.GetString("SurrounderOfFieldNameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرهای محل مأموریت.
        /// </summary>
        public static string tabCityMng {
            get {
                return ResourceManager.GetString("tabCityMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات احکام.
        /// </summary>
        public static string tabContractMng {
            get {
                return ResourceManager.GetString("tabContractMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پرسنل.
        /// </summary>
        public static string tabEmployeeMng {
            get {
                return ResourceManager.GetString("tabEmployeeMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد هزینه.
        /// </summary>
        public static string tabExpenseArticlesMng {
            get {
                return ResourceManager.GetString("tabExpenseArticlesMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات گروه های استخدامی.
        /// </summary>
        public static string tabGroupMng {
            get {
                return ResourceManager.GetString("tabGroupMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناوین شغل ها.
        /// </summary>
        public static string tabJobMng {
            get {
                return ResourceManager.GetString("tabJobMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مانده بدهی های متفرقه.
        /// </summary>
        public static string tabMiscRechargesMng {
            get {
                return ResourceManager.GetString("tabMiscRechargesMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احکام مأموریت.
        /// </summary>
        public static string tabMissionMng {
            get {
                return ResourceManager.GetString("tabMissionMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های ماهانه.
        /// </summary>
        public static string tabMonthlyDataMng {
            get {
                return ResourceManager.GetString("tabMonthlyDataMng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول مالیاتی.
        /// </summary>
        public static string TaxTable {
            get {
                return ResourceManager.GetString("TaxTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول محاسبه مبلغ مالیات.
        /// </summary>
        public static string TaxValueCalculationTable {
            get {
                return ResourceManager.GetString("TaxValueCalculationTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعلوم.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسر از مقدار.
        /// </summary>
        public static string ValueSubtraction {
            get {
                return ResourceManager.GetString("ValueSubtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مقدار.
        /// </summary>
        public static string ValueType {
            get {
                return ResourceManager.GetString("ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متغیرها.
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار متغیر.
        /// </summary>
        public static string VariableValue {
            get {
                return ResourceManager.GetString("VariableValue", resourceCulture);
            }
        }
    }
}
