//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySys.Globalization.Fa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaySys.Globalization.Fa.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم انتخاب شده حذف خواهد شد. تأیید مینمایید؟.
        /// </summary>
        public static string DeleteConfirmationOfItem {
            get {
                return ResourceManager.GetString("DeleteConfirmationOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «XXX» از لیست YYY حذف خواهد گردید. تأیید مینمایید؟.
        /// </summary>
        public static string DeleteConfirmationOfMisc {
            get {
                return ResourceManager.GetString("DeleteConfirmationOfMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً ابتدا رکوردهای استفاده کننده از آیتم را حذف نمایید..
        /// </summary>
        public static string DeleteItemUsers {
            get {
                return ResourceManager.GetString("DeleteItemUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;ValidateOn&apos; can&apos;t be null when there are validaton rules.
        /// </summary>
        public static string DevNullValidateOnPropertyException {
            get {
                return ResourceManager.GetString("DevNullValidateOnPropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً عنوان فیلد حکم را وارد نمایید..
        /// </summary>
        public static string EnterContractFieldTitle {
            get {
                return ResourceManager.GetString("EnterContractFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً کد پرداخت هزینه را وارد فرمایید..
        /// </summary>
        public static string EnterExpenseArticleCode {
            get {
                return ResourceManager.GetString("EnterExpenseArticleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً عنوان پرداخت هزینه را وارد فرمایید..
        /// </summary>
        public static string EnterExpenseArticleTitle {
            get {
                return ResourceManager.GetString("EnterExpenseArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام گروه اصلی را وارد نمایید..
        /// </summary>
        public static string EnterMainGroupName {
            get {
                return ResourceManager.GetString("EnterMainGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً عنوان کسور/پرداخت متفرقه را وارد نمایید..
        /// </summary>
        public static string EnterMiscTitle {
            get {
                return ResourceManager.GetString("EnterMiscTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاًمقدار مؤلفه محاسباتی را وارد نمایید..
        /// </summary>
        public static string EnterParameterValue {
            get {
                return ResourceManager.GetString("EnterParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام زیر گروه را وارد نمایید..
        /// </summary>
        public static string EnterSubGroupName {
            get {
                return ResourceManager.GetString("EnterSubGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً مقدار جدید نرخ مالیات را وارد نمایید..
        /// </summary>
        public static string EnterTaxRowFactor {
            get {
                return ResourceManager.GetString("EnterTaxRowFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً مقدار جدید حد پایانی بازه را وارد نمایید..
        /// </summary>
        public static string EnterTaxRowValueTo {
            get {
                return ResourceManager.GetString("EnterTaxRowValueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً XXX را وارد نمایید..
        /// </summary>
        public static string EnterXXXValue {
            get {
                return ResourceManager.GetString("EnterXXXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده برای &quot;XXX&quot; نامعتبر میباشد..
        /// </summary>
        public static string ErrorValidationXXXValue {
            get {
                return ResourceManager.GetString("ErrorValidationXXXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره اطلاعات با موفقیت انجام گردید..
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً فیلد مورد نظر را انتخاب فرمایید..
        /// </summary>
        public static string SelectContractField {
            get {
                return ResourceManager.GetString("SelectContractField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً ماده هزینه را انتخاب نمایید..
        /// </summary>
        public static string SelectExpenseArticle {
            get {
                return ResourceManager.GetString("SelectExpenseArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً یکی از آیتم ها را انتخاب نمایید..
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً پرداخت متفرقه مورد نظر را انتخاب نمایید..
        /// </summary>
        public static string SelectMiscPayment {
            get {
                return ResourceManager.GetString("SelectMiscPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً فایل تصویری مورد نظر را انتخاب فرمایید.
        /// </summary>
        public static string SelectPhotoFile {
            get {
                return ResourceManager.GetString("SelectPhotoFile", resourceCulture);
            }
        }
    }
}
