//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySys.Globalization.Fa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaySys.Globalization.Fa.Tooltips", typeof(Tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد رکورد جدید (Ctrl+N).
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی جدید.
        /// </summary>
        public static string ButtonAddFiscalYear {
            get {
                return ResourceManager.GetString("ButtonAddFiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن به لیست (Ctrl+I).
        /// </summary>
        public static string ButtonAddToList {
            get {
                return ResourceManager.GetString("ButtonAddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاک کردن فیلتر.
        /// </summary>
        public static string ButtonClearLookup {
            get {
                return ResourceManager.GetString("ButtonClearLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف رکورد (Ctrl+Del).
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف آیتم انتخاب شده (Del).
        /// </summary>
        public static string ButtonDeleteItem {
            get {
                return ResourceManager.GetString("ButtonDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نادیده گرفتن تغییرات (Esc).
        /// </summary>
        public static string ButtonDiscardChanges {
            get {
                return ResourceManager.GetString("ButtonDiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش رکورد (Ctrl+E).
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب فایل تصویر.
        /// </summary>
        public static string ButtonPhotoBrowse {
            get {
                return ResourceManager.GetString("ButtonPhotoBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف تصویر.
        /// </summary>
        public static string ButtonPhotoClear {
            get {
                return ResourceManager.GetString("ButtonPhotoClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگزاری مجدد اطلاعات (F5).
        /// </summary>
        public static string ButtonReload {
            get {
                return ResourceManager.GetString("ButtonReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره تغییرات (Ctrl+S).
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
    }
}
