// <auto-generated />
namespace PaySys.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class subgroupmakemaingroupidrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subgroupmakemaingroupidrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201803151230173_subgroup-make-maingroupid-required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
