// <auto-generated />
namespace PaySys.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtitletosubgroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtitletosubgroup));
        
        string IMigrationMetadata.Id
        {
            get { return "201803150022309_add-title-to-subgroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
