//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaySys.UI.Resource.Globalizaton.Fa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldicEmployee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldicEmployee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaySys.UI.Resource.Globalizaton.Fa.FieldicEmployee", typeof(FieldicEmployee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل تولد.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string CellNo {
            get {
                return ResourceManager.GetString("CellNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پرونده.
        /// </summary>
        public static string DossierNo {
            get {
                return ResourceManager.GetString("DossierNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید اصلی.
        /// </summary>
        public static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن منزل.
        /// </summary>
        public static string HomeTel {
            get {
                return ResourceManager.GetString("HomeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ صدور.
        /// </summary>
        public static string IdCardExportDate {
            get {
                return ResourceManager.GetString("IdCardExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل صدور.
        /// </summary>
        public static string IdCardExportPlace {
            get {
                return ResourceManager.GetString("IdCardExportPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ش شناسنامه.
        /// </summary>
        public static string IdCardNo {
            get {
                return ResourceManager.GetString("IdCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCardNo {
            get {
                return ResourceManager.GetString("NationalCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنلی.
        /// </summary>
        public static string PersonnelCode {
            get {
                return ResourceManager.GetString("PersonnelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدپستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
    }
}
